resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource
- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pull-request
  type: pull-request
  check_every: 15m
  webhook_token: ((github-webhook-token))
  source:
    repository: OdekoTeam/concourse-helm-resource
    access_token: ((git-release-token))
- name: concourse
  type: git
  check_every: 1h
  source:
    branch: master
    password: ((git-release-token))
    uri: https://github.com/OdekoTeam/concourse.git
    username: ((git-user))
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-build-webhook-token))

jobs:
- name: build-concourse-helm-resource
  plan:
  - in_parallel:
    - get: pull-request
      trigger: true
    - get: concourse
  - in_parallel:
    - put: pull-request
      params:
        path: pull-request
        context: build-concourse-helm-resource
        status: pending
      attempts: 3
    - task: build-concourse-helm-resource
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        params:
          DOCKERFILE: pull-request/Dockerfile
          CONTEXT: pull-request
        inputs:
        - name: pull-request
        outputs:
        - name: image
        caches:
        - path: cache
        run:
          path: build
  on_failure:
    do:
    - in_parallel:
      - put: pull-request
        params:
          path: pull-request
          context: build-concourse-helm-resource
          status: failure
        attempts: 3
      - task: slack-message
        file: concourse/tasks/common/slack_pr_message.yml
    - put: slack-alert
      params:
        username: 'concourse'
        icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
        text_file: slack-message/slack-info
        text: |
          :red_circle: *<https://concourse.odeko.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}> failed*
          $TEXT_FILE_CONTENT
        silent: true
      attempts: 3
  on_success:
    do:
    - put: pull-request
      params:
        path: pull-request
        context: build-concourse-helm-resource
        status: success
      attempts: 3
    - put: slack-alert
      params:
        username: 'concourse'
        icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
        text_file: slack-message/slack-info
        text: |
          :thumbsup: *<https://concourse.odeko.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}> succeeded*
          $TEXT_FILE_CONTENT
        silent: true
      attempts: 3
